apiVersion: apps/v1
kind: Deployment
metadata:
  name: spendsense-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: spendsense-backend
  template:
    metadata:
      labels:
        app: spendsense-backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "spendsense-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/spendsense/backend"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/spendsense/backend" -}}
          export MONGO_URI="{{ .Data.data.MONGO_URI }}"
          export JWT_SECRET="{{ .Data.data.JWT_SECRET }}"
          {{- end -}}
    spec:
      containers:
      - name: backend
        image: yuvraj12345678/spendsense-backend:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: spendsense-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: spendsense-secrets
              key: JWT_SECRET
        - name: LOGSTASH_HOST
          valueFrom:
            secretKeyRef:
              name: spendsense-secrets
              key: LOGSTASH_HOST
        - name: LOGSTASH_PORT
          valueFrom:
            secretKeyRef:
              name: spendsense-secrets
              key: LOGSTASH_PORT
        - name: VAULT_SECRET_PATH
          value: "/vault/secrets/config"
---
apiVersion: v1
kind: Service
metadata:
  name: spendsense-backend
spec:
  selector:
    app: spendsense-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spendsense-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70