apiVersion: apps/v1
kind: Deployment
metadata:
  name: spendsense-backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: spendsense-backend
  template:
    metadata:
      labels:
        app: spendsense-backend
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/spendsense-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/spendsense"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: spendsense-secrets
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spendsense-backend
spec:
  selector:
    app: spendsense-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spendsense-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70