---
- name: Install minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Start minikube
  command: minikube start --driver=docker